version: '3'

tasks:
  default:
    deps:
      - install-mac
      - install-linux

  install-mac:
    platforms:
      - darwin
    status:
      - test -d /opt/homebrew
    env:
      NONINTERACTIVE: 1
    cmds:
      - cmd: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  install-linux:
    platforms:
      - linux
    status:
      - test -d /home/linuxbrew/.linuxbrew/bin
    env:
      NONINTERACTIVE: 1
    cmds:
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
